// Code generated by ent, DO NOT EDIT.

package hzwent

import (
	"context"
	"entdemo/hzwent/hzw"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// HzwCreate is the builder for creating a Hzw entity.
type HzwCreate struct {
	config
	mutation *HzwMutation
	hooks    []Hook
}

// SetStuNo sets the "stuNo" field.
func (hc *HzwCreate) SetStuNo(s string) *HzwCreate {
	hc.mutation.SetStuNo(s)
	return hc
}

// SetName sets the "name" field.
func (hc *HzwCreate) SetName(s string) *HzwCreate {
	hc.mutation.SetName(s)
	return hc
}

// SetAge sets the "age" field.
func (hc *HzwCreate) SetAge(i int) *HzwCreate {
	hc.mutation.SetAge(i)
	return hc
}

// SetVersion sets the "version" field.
func (hc *HzwCreate) SetVersion(i int32) *HzwCreate {
	hc.mutation.SetVersion(i)
	return hc
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (hc *HzwCreate) SetNillableVersion(i *int32) *HzwCreate {
	if i != nil {
		hc.SetVersion(*i)
	}
	return hc
}

// SetID sets the "id" field.
func (hc *HzwCreate) SetID(u uuid.UUID) *HzwCreate {
	hc.mutation.SetID(u)
	return hc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (hc *HzwCreate) SetNillableID(u *uuid.UUID) *HzwCreate {
	if u != nil {
		hc.SetID(*u)
	}
	return hc
}

// Mutation returns the HzwMutation object of the builder.
func (hc *HzwCreate) Mutation() *HzwMutation {
	return hc.mutation
}

// Save creates the Hzw in the database.
func (hc *HzwCreate) Save(ctx context.Context) (*Hzw, error) {
	hc.defaults()
	return withHooks(ctx, hc.sqlSave, hc.mutation, hc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (hc *HzwCreate) SaveX(ctx context.Context) *Hzw {
	v, err := hc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hc *HzwCreate) Exec(ctx context.Context) error {
	_, err := hc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hc *HzwCreate) ExecX(ctx context.Context) {
	if err := hc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (hc *HzwCreate) defaults() {
	if _, ok := hc.mutation.Version(); !ok {
		v := hzw.DefaultVersion
		hc.mutation.SetVersion(v)
	}
	if _, ok := hc.mutation.ID(); !ok {
		v := hzw.DefaultID()
		hc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hc *HzwCreate) check() error {
	if _, ok := hc.mutation.StuNo(); !ok {
		return &ValidationError{Name: "stuNo", err: errors.New(`hzwent: missing required field "Hzw.stuNo"`)}
	}
	if _, ok := hc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`hzwent: missing required field "Hzw.name"`)}
	}
	if _, ok := hc.mutation.Age(); !ok {
		return &ValidationError{Name: "age", err: errors.New(`hzwent: missing required field "Hzw.age"`)}
	}
	if _, ok := hc.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`hzwent: missing required field "Hzw.version"`)}
	}
	return nil
}

func (hc *HzwCreate) sqlSave(ctx context.Context) (*Hzw, error) {
	if err := hc.check(); err != nil {
		return nil, err
	}
	_node, _spec := hc.createSpec()
	if err := sqlgraph.CreateNode(ctx, hc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	hc.mutation.id = &_node.ID
	hc.mutation.done = true
	return _node, nil
}

func (hc *HzwCreate) createSpec() (*Hzw, *sqlgraph.CreateSpec) {
	var (
		_node = &Hzw{config: hc.config}
		_spec = sqlgraph.NewCreateSpec(hzw.Table, sqlgraph.NewFieldSpec(hzw.FieldID, field.TypeUUID))
	)
	if id, ok := hc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := hc.mutation.StuNo(); ok {
		_spec.SetField(hzw.FieldStuNo, field.TypeString, value)
		_node.StuNo = value
	}
	if value, ok := hc.mutation.Name(); ok {
		_spec.SetField(hzw.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := hc.mutation.Age(); ok {
		_spec.SetField(hzw.FieldAge, field.TypeInt, value)
		_node.Age = value
	}
	if value, ok := hc.mutation.Version(); ok {
		_spec.SetField(hzw.FieldVersion, field.TypeInt32, value)
		_node.Version = value
	}
	return _node, _spec
}

// HzwCreateBulk is the builder for creating many Hzw entities in bulk.
type HzwCreateBulk struct {
	config
	err      error
	builders []*HzwCreate
}

// Save creates the Hzw entities in the database.
func (hcb *HzwCreateBulk) Save(ctx context.Context) ([]*Hzw, error) {
	if hcb.err != nil {
		return nil, hcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(hcb.builders))
	nodes := make([]*Hzw, len(hcb.builders))
	mutators := make([]Mutator, len(hcb.builders))
	for i := range hcb.builders {
		func(i int, root context.Context) {
			builder := hcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HzwMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hcb *HzwCreateBulk) SaveX(ctx context.Context) []*Hzw {
	v, err := hcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hcb *HzwCreateBulk) Exec(ctx context.Context) error {
	_, err := hcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hcb *HzwCreateBulk) ExecX(ctx context.Context) {
	if err := hcb.Exec(ctx); err != nil {
		panic(err)
	}
}
