// Code generated by ent, DO NOT EDIT.

package hzwent

import (
	"entdemo/hzwent/hzw"
	"entdemo/hzwent/student"
	"entdemo/schema"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	hzwFields := schema.Hzw{}.Fields()
	_ = hzwFields
	// hzwDescVersion is the schema descriptor for version field.
	hzwDescVersion := hzwFields[4].Descriptor()
	// hzw.DefaultVersion holds the default value on creation for the version field.
	hzw.DefaultVersion = hzwDescVersion.Default.(int32)
	// hzwDescID is the schema descriptor for id field.
	hzwDescID := hzwFields[0].Descriptor()
	// hzw.DefaultID holds the default value on creation for the id field.
	hzw.DefaultID = hzwDescID.Default.(func() uuid.UUID)
	studentFields := schema.Student{}.Fields()
	_ = studentFields
	// studentDescVersion is the schema descriptor for version field.
	studentDescVersion := studentFields[4].Descriptor()
	// student.DefaultVersion holds the default value on creation for the version field.
	student.DefaultVersion = studentDescVersion.Default.(int32)
	// studentDescID is the schema descriptor for id field.
	studentDescID := studentFields[0].Descriptor()
	// student.IDValidator is a validator for the "id" field. It is called by the builders before save.
	student.IDValidator = studentDescID.Validators[0].(func(int) error)
}
