// Code generated by Kitex v0.13.1. DO NOT EDIT.

package hzwqueryservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	hzw "kitex_demo/api/kitex/hzw"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"echo1": kitex.NewMethodInfo(
		echo1Handler,
		newHzwQueryServiceEcho1Args,
		newHzwQueryServiceEcho1Result,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	hzwQueryServiceServiceInfo                = NewServiceInfo()
	hzwQueryServiceServiceInfoForClient       = NewServiceInfoForClient()
	hzwQueryServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return hzwQueryServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return hzwQueryServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return hzwQueryServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "HzwQueryService"
	handlerType := (*hzw.HzwQueryService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "hzw",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func echo1Handler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*hzw.HzwQueryServiceEcho1Args)
	realResult := result.(*hzw.HzwQueryServiceEcho1Result)
	success, err := handler.(hzw.HzwQueryService).Echo1(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newHzwQueryServiceEcho1Args() interface{} {
	return hzw.NewHzwQueryServiceEcho1Args()
}

func newHzwQueryServiceEcho1Result() interface{} {
	return hzw.NewHzwQueryServiceEcho1Result()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Echo1(ctx context.Context, req *hzw.Request) (r *hzw.Response, err error) {
	var _args hzw.HzwQueryServiceEcho1Args
	_args.Req = req
	var _result hzw.HzwQueryServiceEcho1Result
	if err = p.c.Call(ctx, "echo1", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
