// Code generated by Kitex v0.13.1. DO NOT EDIT.

package hzwcmdservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	hzw "kitex_demo/api/kitex/hzw"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"echo2": kitex.NewMethodInfo(
		echo2Handler,
		newHzwCmdServiceEcho2Args,
		newHzwCmdServiceEcho2Result,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	hzwCmdServiceServiceInfo                = NewServiceInfo()
	hzwCmdServiceServiceInfoForClient       = NewServiceInfoForClient()
	hzwCmdServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return hzwCmdServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return hzwCmdServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return hzwCmdServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "HzwCmdService"
	handlerType := (*hzw.HzwCmdService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "hzw",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func echo2Handler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*hzw.HzwCmdServiceEcho2Args)
	realResult := result.(*hzw.HzwCmdServiceEcho2Result)
	success, err := handler.(hzw.HzwCmdService).Echo2(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newHzwCmdServiceEcho2Args() interface{} {
	return hzw.NewHzwCmdServiceEcho2Args()
}

func newHzwCmdServiceEcho2Result() interface{} {
	return hzw.NewHzwCmdServiceEcho2Result()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Echo2(ctx context.Context, req *hzw.Request) (r *hzw.Response, err error) {
	var _args hzw.HzwCmdServiceEcho2Args
	_args.Req = req
	var _result hzw.HzwCmdServiceEcho2Result
	if err = p.c.Call(ctx, "echo2", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
