// Code generated by ent, DO NOT EDIT.

package hzwent

import (
	"context"
	"entdemo/hzwent/hzw"
	"entdemo/hzwent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HzwDelete is the builder for deleting a Hzw entity.
type HzwDelete struct {
	config
	hooks    []Hook
	mutation *HzwMutation
}

// Where appends a list predicates to the HzwDelete builder.
func (hd *HzwDelete) Where(ps ...predicate.Hzw) *HzwDelete {
	hd.mutation.Where(ps...)
	return hd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (hd *HzwDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, hd.sqlExec, hd.mutation, hd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (hd *HzwDelete) ExecX(ctx context.Context) int {
	n, err := hd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (hd *HzwDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(hzw.Table, sqlgraph.NewFieldSpec(hzw.FieldID, field.TypeUUID))
	if ps := hd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, hd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	hd.mutation.done = true
	return affected, err
}

// HzwDeleteOne is the builder for deleting a single Hzw entity.
type HzwDeleteOne struct {
	hd *HzwDelete
}

// Where appends a list predicates to the HzwDelete builder.
func (hdo *HzwDeleteOne) Where(ps ...predicate.Hzw) *HzwDeleteOne {
	hdo.hd.mutation.Where(ps...)
	return hdo
}

// Exec executes the deletion query.
func (hdo *HzwDeleteOne) Exec(ctx context.Context) error {
	n, err := hdo.hd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{hzw.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (hdo *HzwDeleteOne) ExecX(ctx context.Context) {
	if err := hdo.Exec(ctx); err != nil {
		panic(err)
	}
}
