// Code generated by Kitex v0.12.3. DO NOT EDIT.

package byby

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	api "wiredemo/pkg/kitex/kitex_gen/api"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"byby": kitex.NewMethodInfo(
		bybyHandler,
		newBybyBybyArgs,
		newBybyBybyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	bybyServiceInfo                = NewServiceInfo()
	bybyServiceInfoForClient       = NewServiceInfoForClient()
	bybyServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return bybyServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return bybyServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return bybyServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Byby"
	handlerType := (*api.Byby)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func bybyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.BybyBybyArgs)
	realResult := result.(*api.BybyBybyResult)
	success, err := handler.(api.Byby).Byby(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBybyBybyArgs() interface{} {
	return api.NewBybyBybyArgs()
}

func newBybyBybyResult() interface{} {
	return api.NewBybyBybyResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Byby(ctx context.Context, req *api.BybyRequest) (r *api.BybyResponse, err error) {
	var _args api.BybyBybyArgs
	_args.Req = req
	var _result api.BybyBybyResult
	if err = p.c.Call(ctx, "byby", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
