// Code generated by aic-ent, DO NOT EDIT
// Code generated by aic-ent, DO NOT EDIT
// Code generated by aic-ent, DO NOT EDIT

package model

const TableNameProduct = "STUDENT"

// Student mapped from table STUDENT
type Student struct {
   //Age  int `gorm:"column:Age" json:"Age"`
   //Id  int64 `gorm:"column:ID;primaryKey" json:"Id"`
   //Name  string `gorm:"column:Name;not null" json:"Name"`
   //Version  int32 `gorm:"column:Version;not null" json:"Version"`
   Id  int64 `gorm:"column:ID;primaryKey" json:"Id"`
   Name  string `gorm:"column:NAME;not null" json:"Name"`
   Age  int `gorm:"column:AGE" json:"Age"`
   Version  int32 `gorm:"column:VERSION;not null" json:"Version"`
}
type FindByNameArg struct {
   Name  string
}

// TableName STUDENT table name
func (*Student) TableName() string {
   return TableNameProduct
}