// Code generated by Kitex v0.13.1. DO NOT EDIT.
package helloprotoservice

import (
	server "github.com/cloudwego/kitex/server"
	helloproto "kitex_demo/api/kitex/helloproto"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler helloproto.HelloProtoService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler helloproto.HelloProtoService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
