// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wirehello

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeEvent 声明injector的函数签名
func InitializeEvent(msg string) Event {
	message := NewMessage(msg)
	greeter := NewGreeter(message)
	event := NewEvent(greeter)
	return event
}

func InitApp() *App {
	serviceA := _wireServiceAValue
	app := NewAppA(serviceA)
	return app
}

var (
	_wireServiceAValue = &ServiceA{}
)

// wire.go:

var wireSet = wire.NewSet(wire.Value(&ServiceA{}), wire.Value(&ServiceB{}), NewAppA)
