// Code generated by aic-ent, DO NOT EDIT
// Code generated by aic-ent, DO NOT EDIT
// Code generated by aic-ent, DO NOT EDIT

package dao
import (
    "context"
    "wiredemo/internal/repository/model"
    db "aic.com/pkg/aicgormdb"
)


type IHzw2Dao interface{
    InsertOne(ctx context.Context,arg *model.Hzw2)(int64,error)
    FindByPrimaryKey(ctx context.Context, Id uint) (*model.Hzw2,error)
    UpdateByPrimaryKey(ctx context.Context,arg *model.Hzw2)(int64,error)
    UpdateByPriIngoreNullCols(ctx context.Context,arg *model.Hzw2)(int64,error)
    DeleteByPrimaryKey(ctx context.Context, Id uint)(int64,error)
    FindByName(ctx context.Context,Name string)([]model.Hzw2,error)
}

type Hzw2Dao struct{
	*db.Repository
}

// NewHzw2Dao get dao instance
func NewHzw2Dao(repository *db.Repository) IHzw2Dao{
    return &Hzw2Dao{
        Repository: repository,
    }
}

func (dao *Hzw2Dao) InsertOne(ctx context.Context,arg *model.Hzw2)(int64,error){
    result:=dao.DB(ctx).Create(arg)
    return result.RowsAffected, result.Error
}

func (dao *Hzw2Dao) FindByPrimaryKey(ctx context.Context, Id uint) (*model.Hzw2,error) {
   findRes :=&model.Hzw2{}
   result:=dao.DB(ctx).Where("ID",Id).Find(findRes)
   return findRes,result.Error
}

func (dao *Hzw2Dao) UpdateByPrimaryKey(ctx context.Context,arg *model.Hzw2)(int64,error){
      result:=dao.DB(ctx).Save(arg)
      return result.RowsAffected, result.Error
}

func (dao *Hzw2Dao) UpdateByPriIngoreNullCols(ctx context.Context,arg *model.Hzw2)(int64,error){
      result:=dao.DB(ctx).Model(arg).Updates(arg)
      return result.RowsAffected, result.Error
}

func (dao *Hzw2Dao) DeleteByPrimaryKey(ctx context.Context, Id uint)(int64,error){
      result:=dao.DB(ctx).Where("ID",Id).Delete(&model.Hzw2{})
      return result.RowsAffected, result.Error
}

func (dao *Hzw2Dao) FindByName(ctx context.Context,Name string)([]model.Hzw2,error){
   var list []model.Hzw2
   result:=dao.DB(ctx).Where("NAME", Name).Find(&list)
   return list,result.Error
}