// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: exec.sql

package tutorial

import (
	"context"
)

const createStudent = `-- name: CreateStudent :exec
INSERT INTO students (student_no, name, age) VALUES(?, ?, ?)
`

type CreateStudentParams struct {
	StudentNo string
	Name      string
	Age       int64
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) error {
	_, err := q.db.ExecContext(ctx, createStudent, arg.StudentNo, arg.Name, arg.Age)
	return err
}
