// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package tutorial

type Student struct {
	ID        int64
	StudentNo string
	Name      string
	Age       int64
}

type User struct {
	ID   int32
	Name string
}
