// Code generated by thriftgo (0.4.1). DO NOT EDIT.

package hzw

import (
	"context"
	"fmt"
)

type Request struct {
	Message string `thrift:"message,1" frugal:"1,default,string" json:"message"`
}

func NewRequest() *Request {
	return &Request{}
}

func (p *Request) InitDefault() {
}

func (p *Request) GetMessage() (v string) {
	return p.Message
}
func (p *Request) SetMessage(val string) {
	p.Message = val
}

func (p *Request) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Request(%+v)", *p)
}

var fieldIDToName_Request = map[int16]string{
	1: "message",
}

type Response struct {
	Message string `thrift:"message,1" frugal:"1,default,string" json:"message"`
}

func NewResponse() *Response {
	return &Response{}
}

func (p *Response) InitDefault() {
}

func (p *Response) GetMessage() (v string) {
	return p.Message
}
func (p *Response) SetMessage(val string) {
	p.Message = val
}

func (p *Response) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Response(%+v)", *p)
}

var fieldIDToName_Response = map[int16]string{
	1: "message",
}

type HzwCmdService interface {
	Echo2(ctx context.Context, req *Request) (r *Response, err error)
}

type HzwCmdServiceEcho2Args struct {
	Req *Request `thrift:"req,1" frugal:"1,default,Request" json:"req"`
}

func NewHzwCmdServiceEcho2Args() *HzwCmdServiceEcho2Args {
	return &HzwCmdServiceEcho2Args{}
}

func (p *HzwCmdServiceEcho2Args) InitDefault() {
}

var HzwCmdServiceEcho2Args_Req_DEFAULT *Request

func (p *HzwCmdServiceEcho2Args) GetReq() (v *Request) {
	if !p.IsSetReq() {
		return HzwCmdServiceEcho2Args_Req_DEFAULT
	}
	return p.Req
}
func (p *HzwCmdServiceEcho2Args) SetReq(val *Request) {
	p.Req = val
}

func (p *HzwCmdServiceEcho2Args) IsSetReq() bool {
	return p.Req != nil
}

func (p *HzwCmdServiceEcho2Args) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HzwCmdServiceEcho2Args(%+v)", *p)
}

var fieldIDToName_HzwCmdServiceEcho2Args = map[int16]string{
	1: "req",
}

type HzwCmdServiceEcho2Result struct {
	Success *Response `thrift:"success,0,optional" frugal:"0,optional,Response" json:"success,omitempty"`
}

func NewHzwCmdServiceEcho2Result() *HzwCmdServiceEcho2Result {
	return &HzwCmdServiceEcho2Result{}
}

func (p *HzwCmdServiceEcho2Result) InitDefault() {
}

var HzwCmdServiceEcho2Result_Success_DEFAULT *Response

func (p *HzwCmdServiceEcho2Result) GetSuccess() (v *Response) {
	if !p.IsSetSuccess() {
		return HzwCmdServiceEcho2Result_Success_DEFAULT
	}
	return p.Success
}
func (p *HzwCmdServiceEcho2Result) SetSuccess(x interface{}) {
	p.Success = x.(*Response)
}

func (p *HzwCmdServiceEcho2Result) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *HzwCmdServiceEcho2Result) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HzwCmdServiceEcho2Result(%+v)", *p)
}

var fieldIDToName_HzwCmdServiceEcho2Result = map[int16]string{
	0: "success",
}

type HzwQueryService interface {
	Echo1(ctx context.Context, req *Request) (r *Response, err error)
}

type HzwQueryServiceEcho1Args struct {
	Req *Request `thrift:"req,1" frugal:"1,default,Request" json:"req"`
}

func NewHzwQueryServiceEcho1Args() *HzwQueryServiceEcho1Args {
	return &HzwQueryServiceEcho1Args{}
}

func (p *HzwQueryServiceEcho1Args) InitDefault() {
}

var HzwQueryServiceEcho1Args_Req_DEFAULT *Request

func (p *HzwQueryServiceEcho1Args) GetReq() (v *Request) {
	if !p.IsSetReq() {
		return HzwQueryServiceEcho1Args_Req_DEFAULT
	}
	return p.Req
}
func (p *HzwQueryServiceEcho1Args) SetReq(val *Request) {
	p.Req = val
}

func (p *HzwQueryServiceEcho1Args) IsSetReq() bool {
	return p.Req != nil
}

func (p *HzwQueryServiceEcho1Args) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HzwQueryServiceEcho1Args(%+v)", *p)
}

var fieldIDToName_HzwQueryServiceEcho1Args = map[int16]string{
	1: "req",
}

type HzwQueryServiceEcho1Result struct {
	Success *Response `thrift:"success,0,optional" frugal:"0,optional,Response" json:"success,omitempty"`
}

func NewHzwQueryServiceEcho1Result() *HzwQueryServiceEcho1Result {
	return &HzwQueryServiceEcho1Result{}
}

func (p *HzwQueryServiceEcho1Result) InitDefault() {
}

var HzwQueryServiceEcho1Result_Success_DEFAULT *Response

func (p *HzwQueryServiceEcho1Result) GetSuccess() (v *Response) {
	if !p.IsSetSuccess() {
		return HzwQueryServiceEcho1Result_Success_DEFAULT
	}
	return p.Success
}
func (p *HzwQueryServiceEcho1Result) SetSuccess(x interface{}) {
	p.Success = x.(*Response)
}

func (p *HzwQueryServiceEcho1Result) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *HzwQueryServiceEcho1Result) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HzwQueryServiceEcho1Result(%+v)", *p)
}

var fieldIDToName_HzwQueryServiceEcho1Result = map[int16]string{
	0: "success",
}
