// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Hzw is the predicate function for hzw builders.
type Hzw func(*sql.Selector)

// Student is the predicate function for student builders.
type Student func(*sql.Selector)
