// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// HzwColumns holds the columns for the "hzw" table.
	HzwColumns = []*schema.Column{
		{Name: "HZW_ID", Type: field.TypeUUID},
		{Name: "STU_NO", Type: field.TypeString},
		{Name: "NAME", Type: field.TypeString},
		{Name: "AGE", Type: field.TypeInt},
		{Name: "VERSION", Type: field.TypeInt32, Default: 0},
	}
	// HzwTable holds the schema information for the "hzw" table.
	HzwTable = &schema.Table{
		Name:       "hzw",
		Columns:    HzwColumns,
		PrimaryKey: []*schema.Column{HzwColumns[0]},
	}
	// StudentColumns holds the columns for the "student" table.
	StudentColumns = []*schema.Column{
		{Name: "ID", Type: field.TypeInt, Increment: true},
		{Name: "STU_NO", Type: field.TypeString},
		{Name: "NAME", Type: field.TypeString},
		{Name: "AGE", Type: field.TypeInt},
		{Name: "VERSION", Type: field.TypeInt32, Default: 0},
	}
	// StudentTable holds the schema information for the "student" table.
	StudentTable = &schema.Table{
		Name:       "student",
		Columns:    StudentColumns,
		PrimaryKey: []*schema.Column{StudentColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		HzwTable,
		StudentTable,
	}
)

func init() {
	HzwTable.Annotation = &entsql.Annotation{
		Table: "hzw",
	}
	StudentTable.Annotation = &entsql.Annotation{
		Table: "student",
	}
}
