// Code generated by Kitex v0.12.3. DO NOT EDIT.

package hzwservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	hzw "wiredemo/api/kitex/hzw"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateHzw(ctx context.Context, hzwDto *hzw.HzwDto, callOptions ...callopt.Option) (r *hzw.HzwDto, err error)
	GetHzw(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hzw.HzwDto, err error)
	CreateHzwTxTest(ctx context.Context, hzwDto *hzw.HzwDto, callOptions ...callopt.Option) (r *hzw.HzwDto, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kHzwServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kHzwServiceClient struct {
	*kClient
}

func (p *kHzwServiceClient) CreateHzw(ctx context.Context, hzwDto *hzw.HzwDto, callOptions ...callopt.Option) (r *hzw.HzwDto, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateHzw(ctx, hzwDto)
}

func (p *kHzwServiceClient) GetHzw(ctx context.Context, id int64, callOptions ...callopt.Option) (r *hzw.HzwDto, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetHzw(ctx, id)
}

func (p *kHzwServiceClient) CreateHzwTxTest(ctx context.Context, hzwDto *hzw.HzwDto, callOptions ...callopt.Option) (r *hzw.HzwDto, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateHzwTxTest(ctx, hzwDto)
}
