// Code generated by aic-ent, DO NOT EDIT
// Code generated by aic-ent, DO NOT EDIT
// Code generated by aic-ent, DO NOT EDIT

package model
import (
	"time"
)

const TableNameProduct = "USER_TEST"

// UserTest mapped from table USER_TEST
type UserTest struct {
   Amt  float64 `gorm:"column:AMT" json:"Amt"`
   Birthday  *time.Time `gorm:"AUTOCREATETIME;AUTOUPDATETIME;column:BIRTHDAY" json:"Birthday"`
   IdNo  string `gorm:"column:ID_NO;not null;uniqueIndex:USER_TEST01,priority:1" json:"IdNo"`
   IdType  string `gorm:"column:ID_TYPE;not null;uniqueIndex:USER_TEST01,priority:2" json:"IdType"`
   UserId  int64 `gorm:"column:USER_ID;primaryKey;not null" json:"UserId"`
   UserName  string `gorm:"column:USER_NAME;not null;index:USER_TEST02,priority:1" json:"UserName"`
}
type FindByAAAArg struct {
   IdNo  string
   Birthday  *time.Time
}

// TableName USER_TEST table name
func (*UserTest) TableName() string {
   return TableNameProduct
}